# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-05-01 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Twittertext',
        ),
    ]
